[package]
name = "api_examples"
version = "0.1.0"
authors = ["diamondrod"]
edition = "2021"
description = """
NOT A PACKAGE TO PUBLISH.

This module provides examples of using `api` feature of `kxkdb` library. The functions defined in
 the library are used for simple tests.
"""

[lib]
crate-type=["cdylib"]

[dependencies]
libc="0.2"
kxkdb={path="../kxkdb", features=["api"]}
